### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by sanjayankur31** [clwyatt/DiffusionKurtosisFit#2]
We're unable to build it from source now. This is the complete build log:

```
Mock Version: 1.4.16
Mock Version: 1.4.16
ENTER ['do_with_status'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/DiffusionKurtosisFit.spec'], chrootPath='/var/lib/mock/f31-build-16929477-1220867/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7f94482ed4e0>timeout=172800uid=1000gid=425user='mockbuild'nspawn_args=[]unshare_net=TrueprintOutput=False)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/DiffusionKurtosisFit.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell False
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1563667200
Wrote: /builddir/build/SRPMS/DiffusionKurtosisFit-0.1.1-13.fc31.src.rpm
Child return code was: 0
ENTER ['do_with_status'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/DiffusionKurtosisFit.spec'], chrootPath='/var/lib/mock/f31-build-16929477-1220867/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7f94482ed4e0>timeout=172800uid=1000gid=425user='mockbuild'nspawn_args=[]unshare_net=TrueprintOutput=False)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/DiffusionKurtosisFit.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell False
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1563667200
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.49tuZc
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf DiffusionKurtosisFit-0.1.1
+ /usr/bin/gzip -dc /builddir/build/SOURCES/DiffusionKurtosisFit-0.1.1.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd DiffusionKurtosisFit-0.1.1
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ sed -i -e s/itkvcl/vcl/ -e '/ADD_LIBRARY/s/vul /vul STATIC /' Utilities/vul/CMakeLists.txt
+ rm -rf build/
+ mkdir build/
+ RPM_EC=0
BUILDSTDERR: ++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.TeuRMb
+ umask 022
+ cd /builddir/build/BUILD
+ cd DiffusionKurtosisFit-0.1.1
+ CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -std=gnu++98'
+ pushd build/
+ export ITK_DIR=/usr/lib64/cmake/InsightToolkit/
+ ITK_DIR=/usr/lib64/cmake/InsightToolkit/
+ export LIBMINC_DIR=/usr/lib64/cmake/LIBMINC/
+ LIBMINC_DIR=/usr/lib64/cmake/LIBMINC/
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CFLAGS
+ CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -std=gnu++98'
+ export CXXFLAGS
+ FFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
+ export LDFLAGS
+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON ../
BUILDSTDERR: CMake Warning (dev) at Code/CMakeLists.txt:9 (ADD_EXECUTABLE):
BUILDSTDERR:   Policy CMP0028 is not set: Double colon in target name means ALIAS or
BUILDSTDERR:   IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
BUILDSTDERR:   Use the cmake_policy command to set the policy and suppress this warning.
BUILDSTDERR:   Target "dtiscalars" links to target "GTest::GTest" but the target was not
BUILDSTDERR:   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
BUILDSTDERR:   an ALIAS target is missing?
BUILDSTDERR: This warning is for project developers.  Use -Wno-dev to suppress it.
BUILDSTDERR: CMake Warning (dev) at Code/CMakeLists.txt:9 (ADD_EXECUTABLE):
BUILDSTDERR:   Policy CMP0028 is not set: Double colon in target name means ALIAS or
BUILDSTDERR:   IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
BUILDSTDERR:   Use the cmake_policy command to set the policy and suppress this warning.
BUILDSTDERR:   Target "dtiscalars" links to target "GTest::Main" but the target was not
BUILDSTDERR:   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
BUILDSTDERR:   an ALIAS target is missing?
BUILDSTDERR: This warning is for project developers.  Use -Wno-dev to suppress it.
BUILDSTDERR: CMake Warning (dev) at Code/CMakeLists.txt:14 (ADD_EXECUTABLE):
BUILDSTDERR:   Policy CMP0028 is not set: Double colon in target name means ALIAS or
BUILDSTDERR:   IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
BUILDSTDERR:   Use the cmake_policy command to set the policy and suppress this warning.
BUILDSTDERR:   Target "dkiscalars" links to target "GTest::GTest" but the target was not
BUILDSTDERR:   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
BUILDSTDERR:   an ALIAS target is missing?
BUILDSTDERR: This warning is for project developers.  Use -Wno-dev to suppress it.
BUILDSTDERR: CMake Warning (dev) at Code/CMakeLists.txt:14 (ADD_EXECUTABLE):
BUILDSTDERR:   Policy CMP0028 is not set: Double colon in target name means ALIAS or
BUILDSTDERR:   IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
BUILDSTDERR:   Use the cmake_policy command to set the policy and suppress this warning.
BUILDSTDERR:   Target "dkiscalars" links to target "GTest::Main" but the target was not
BUILDSTDERR:   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
BUILDSTDERR:   an ALIAS target is missing?
BUILDSTDERR: This warning is for project developers.  Use -Wno-dev to suppress it.
BUILDSTDERR: CMake Warning (dev) at Code/CMakeLists.txt:2 (ADD_EXECUTABLE):
BUILDSTDERR:   Policy CMP0028 is not set: Double colon in target name means ALIAS or
BUILDSTDERR:   IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
BUILDSTDERR:   Use the cmake_policy command to set the policy and suppress this warning.
BUILDSTDERR:   Target "dkifit" links to target "GTest::GTest" but the target was not
BUILDSTDERR:   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
BUILDSTDERR:   an ALIAS target is missing?
BUILDSTDERR: This warning is for project developers.  Use -Wno-dev to suppress it.
BUILDSTDERR: CMake Warning (dev) at Code/CMakeLists.txt:2 (ADD_EXECUTABLE):
BUILDSTDERR:   Policy CMP0028 is not set: Double colon in target name means ALIAS or
BUILDSTDERR:   IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
BUILDSTDERR:   Use the cmake_policy command to set the policy and suppress this warning.
BUILDSTDERR:   Target "dkifit" links to target "GTest::Main" but the target was not found.
BUILDSTDERR:   Perhaps a find_package() call is missing for an IMPORTED target, or an
BUILDSTDERR:   ALIAS target is missing?
BUILDSTDERR: This warning is for project developers.  Use -Wno-dev to suppress it.
BUILDSTDERR: CMake Warning:
BUILDSTDERR:   Manually-specified variables were not used by the project:
BUILDSTDERR:     CMAKE_C_FLAGS_RELEASE
BUILDSTDERR:     CMAKE_Fortran_FLAGS_RELEASE
BUILDSTDERR:     INCLUDE_INSTALL_DIR
BUILDSTDERR:     LIB_INSTALL_DIR
BUILDSTDERR:     LIB_SUFFIX
BUILDSTDERR:     SHARE_INSTALL_PREFIX
BUILDSTDERR:     SYSCONF_INSTALL_DIR
+ make -j1
BUILDSTDERR: In file included from /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul/vul_printf.h:23,
BUILDSTDERR:                  from /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul/vul_printf.cxx:11:
BUILDSTDERR: /usr/include/vxl/vcl/vcl_iosfwd.h:11:5: warning: #warning "This header will be removed in future versions of VXL.  Use equivalent C++11 header instead. see: vxl/scripts/UseStandardHeaders.py" [-Wcpp]
BUILDSTDERR:    11 |   # warning "This header will be removed in future versions of VXL.  Use equivalent C++11 header instead. see: vxl/scripts/UseStandardHeaders.py"
BUILDSTDERR:       |     ^~~~~~~
BUILDSTDERR: In file included from /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul/vul_printf.cxx:13:
BUILDSTDERR: /usr/include/vxl/vcl/vcl_cstdarg.h:11:5: warning: #warning "This header will be removed in future versions of VXL.  Use equivalent C++11 header instead. see: vxl/scripts/UseStandardHeaders.py" [-Wcpp]
BUILDSTDERR:    11 |   # warning "This header will be removed in future versions of VXL.  Use equivalent C++11 header instead. see: vxl/scripts/UseStandardHeaders.py"
BUILDSTDERR:       |     ^~~~~~~
BUILDSTDERR: In file included from /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul/vul_printf.cxx:14:
BUILDSTDERR: /usr/include/vxl/vcl/vcl_iostream.h:11:5: warning: #warning "This header will be removed in future versions of VXL.  Use equivalent C++11 header instead. see: vxl/scripts/UseStandardHeaders.py" [-Wcpp]
BUILDSTDERR:    11 |   # warning "This header will be removed in future versions of VXL.  Use equivalent C++11 header instead. see: vxl/scripts/UseStandardHeaders.py"
BUILDSTDERR:       |     ^~~~~~~
BUILDSTDERR: In file included from /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul/vul_printf.cxx:15:
BUILDSTDERR: /usr/include/vxl/vcl/vcl_cstdio.h:11:5: warning: #warning "This header will be removed in future versions of VXL.  Use equivalent C++11 header instead. see: vxl/scripts/UseStandardHeaders.py" [-Wcpp]
BUILDSTDERR:    11 |   # warning "This header will be removed in future versions of VXL.  Use equivalent C++11 header instead. see: vxl/scripts/UseStandardHeaders.py"
BUILDSTDERR:       |     ^~~~~~~
BUILDSTDERR: In file included from /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul/vul_printf.cxx:11:
BUILDSTDERR: /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul/vul_printf.h:30:1: error: 'vcl_ostream' does not name a type; did you mean 'vcl_iostream_h_'?
BUILDSTDERR:    30 | vcl_ostream& vul_printf(vcl_ostream&, char const* fmt, ...);
BUILDSTDERR:       | ^~~~~~~~~~~
BUILDSTDERR:       | vcl_iostream_h_
BUILDSTDERR: /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul/vul_printf.cxx:17:1: error: 'vcl_ostream' does not name a type; did you mean 'vcl_iostream_h_'?
BUILDSTDERR:    17 | vcl_ostream& vul_printf(vcl_ostream& s, char const * fmt, ...)
BUILDSTDERR:       | ^~~~~~~~~~~
BUILDSTDERR:       | vcl_iostream_h_
BUILDSTDERR: make[2]: *** [Utilities/vul/CMakeFiles/vul.dir/build.make:66: Utilities/vul/CMakeFiles/vul.dir/vul_printf.cxx.o] Error 1
BUILDSTDERR: make[1]: *** [CMakeFiles/Makefile2:1159: Utilities/vul/CMakeFiles/vul.dir/all] Error 2
BUILDSTDERR: make: *** [Makefile:120: all] Error 2
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.TeuRMb (%build)
BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.TeuRMb (%build)
~/build/BUILD/DiffusionKurtosisFit-0.1.1/build ~/build/BUILD/DiffusionKurtosisFit-0.1.1
-- The C compiler identification is GNU 9.1.1
-- The CXX compiler identification is GNU 9.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build
/usr/bin/cmake -S/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1 -B/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build/CMakeFiles /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build'
make -f Utilities/vul/CMakeFiles/vul.dir/build.make Utilities/vul/CMakeFiles/vul.dir/depend
make[2]: Entering directory '/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build'
cd /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1 /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build/Utilities/vul /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build/Utilities/vul/CMakeFiles/vul.dir/DependInfo.cmake --color=
Scanning dependencies of target vul
make[2]: Leaving directory '/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build'
make -f Utilities/vul/CMakeFiles/vul.dir/build.make Utilities/vul/CMakeFiles/vul.dir/build
make[2]: Entering directory '/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build'
[  7%] Building CXX object Utilities/vul/CMakeFiles/vul.dir/vul_printf.cxx.o
cd /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build/Utilities/vul && /usr/bin/c++  -DITK_IO_FACTORY_REGISTER_MANAGER -DvtkRenderingCore_AUTOINIT="3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL2)" -I/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build/ITKFactoryRegistration -I/usr/include/eigen3 -I/usr/include/freetype2 -I/usr/include/vtk -I/usr/include/libminc -I/usr/lib64/usr/include/gdcm -I/usr/include/vxl/core -I/usr/include/vxl/vcl -I/usr/include/vxl/v3p/netlib -I/usr/include/InsightToolkit -I/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul -I/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Code  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -std=gnu++98    -o CMakeFiles/vul.dir/vul_printf.cxx.o -c /builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/Utilities/vul/vul_printf.cxx
make[2]: Leaving directory '/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build'
make[1]: Leaving directory '/builddir/build/BUILD/DiffusionKurtosisFit-0.1.1/build'
RPM build errors:
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 736, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/DiffusionKurtosisFit.spec
```

VXL has new releases and was updated in Fedora to version 2.0.4. So this could be a result of that. Any ideas? 

(I also noticed that there have been no recent commits. Is this still being maintained?)

Build log files are attached.
[build.txt](https://github.com/clwyatt/DiffusionKurtosisFit/files/3414514/build.txt)
[root.txt](https://github.com/clwyatt/DiffusionKurtosisFit/files/3414515/root.txt)

**Comment by sanjayankur31** [comment]
Friendly ping---any updates here please?

**Comment by sanjayankur31** [comment]
Hello,

Any help here please?

Cheers
